/**
 * Firebase Configuration
 * =====================
 * Credentials come from js/firebase-credentials.js (window.FIREBASE_CREDS),
 * which is generated by GitHub Actions from the FIREBASE_CONFIG secret.
 * This file is NEVER overwritten by CI — all logic lives here safely.
 */

function initFirebaseRuntime() {
  if (window.__firebaseRuntimeInitialized) return;
  window.__firebaseRuntimeInitialized = true;

  // Initialize Firebase (only once).
  // Credentials come from firebase-credentials.js (window.FIREBASE_CREDS).
  // Avoid declaring `const firebaseConfig` — the credentials file (written by
  // GitHub Actions secret) may already declare it, causing a SyntaxError.
  if (!firebase.apps.length) {
    firebase.initializeApp(window.FIREBASE_CREDS || {
      apiKey: "PLACEHOLDER_API_KEY",
      authDomain: "PLACEHOLDER_AUTHDOMAIN",
      projectId: "PLACEHOLDER_PROJECT_ID",
      storageBucket: "PLACEHOLDER_BUCKET",
      messagingSenderId: "PLACEHOLDER_SENDER_ID",
      appId: "PLACEHOLDER_APP_ID",
      measurementId: "PLACEHOLDER_MEASUREMENT_ID"
    });
  }

  // ── Offline persistence ────────────────────────────────────────────────
  // Enables IndexedDB cache for Firestore. With this active:
  //   • Reads served from local cache when offline.
  //   • Writes performed offline are queued in IndexedDB and synced to
  //     the server automatically when the network returns.
  //   • Latency-compensated UI: a saveDeck() call returns instantly even
  //     offline; the doc appears in queries immediately and is reconciled
  //     with the server later.
  // Must be called BEFORE any firestore() read/write — this file runs
  // before firebase-globals.js which is the first consumer. Uses the
  // multi-tab variant so two browser tabs on the same device can both
  // access the cache safely.
  //
  // window.__firestorePersistenceReady resolves when persistence is
  // enabled (or rejects with the failure reason) — UI can await it
  // before showing offline-capable affordances.
  window.__firestorePersistenceReady = (function() {
    try {
      return firebase.firestore().enableMultiTabIndexedDbPersistence()
        .then(function() {
          window.__firestorePersistenceEnabled = true;
          console.info('[Firestore] Offline persistence enabled (multi-tab)');
          return true;
        })
        .catch(function(err) {
          window.__firestorePersistenceEnabled = false;
          window.__firestorePersistenceError = (err && err.code) || 'unknown';
          if (err && err.code === 'failed-precondition') {
            console.warn('[Firestore] Persistence disabled: another tab without multi-tab persistence is open');
          } else if (err && err.code === 'unimplemented') {
            console.warn('[Firestore] Persistence disabled: browser does not support required features (private mode?)');
          } else {
            console.warn('[Firestore] Persistence setup failed:', err);
          }
          return false;
        });
    } catch (e) {
      window.__firestorePersistenceEnabled = false;
      window.__firestorePersistenceError = 'init-failed';
      console.warn('[Firestore] Persistence init threw:', e);
      return Promise.resolve(false);
    }
  })();

  // Auth state observer — handlers are defined in firebase-globals.js.
  const _fbDev = typeof DEV_MODE !== 'undefined' ? DEV_MODE : false;
  firebase.auth().onAuthStateChanged(function(user) {
    if (user) {
      console.info('[Auth] Firebase state: signed in', user.email || user.uid || 'unknown-user');
      if (_fbDev) console.log('✓ User signed in:', user.email);
      if (typeof onUserSignedIn === 'function') {
        onUserSignedIn(user);
      } else {
        window.__pendingAuthUser = user;
        console.warn('[Auth] onUserSignedIn handler not ready yet; queued auth state for later sync');
      }
    } else {
      console.info('[Auth] Firebase state: signed out');
      if (_fbDev) console.log('✗ User signed out');
      if (typeof onUserSignedOut === 'function') {
        onUserSignedOut();
      } else {
        window.__pendingAuthUser = null;
        console.warn('[Auth] onUserSignedOut handler not ready yet; queued auth state for later sync');
      }
    }
  });
}

// Run synchronously — the Firebase SDK scripts are already loaded at this point,
// and firebase-globals.js (next in load order) needs firebase.auth() immediately.
initFirebaseRuntime();
