/**
 * Firebase Configuration
 * =====================
 * Credentials come from js/firebase-credentials.js (window.FIREBASE_CREDS),
 * which is generated by GitHub Actions from the FIREBASE_CONFIG secret.
 * This file is NEVER overwritten by CI — all logic lives here safely.
 */

// Initialize Firebase (only once).
// Credentials come from firebase-credentials.js (window.FIREBASE_CREDS).
// Avoid declaring `const firebaseConfig` — the credentials file (written by
// GitHub Actions secret) may already declare it, causing a SyntaxError.
if (!firebase.apps.length) {
  const _creds = Object.assign({}, window.FIREBASE_CREDS || {
    apiKey: "PLACEHOLDER_API_KEY",
    authDomain: "PLACEHOLDER_AUTHDOMAIN",
    projectId: "PLACEHOLDER_PROJECT_ID",
    storageBucket: "PLACEHOLDER_BUCKET",
    messagingSenderId: "PLACEHOLDER_SENDER_ID",
    appId: "PLACEHOLDER_APP_ID",
    measurementId: "PLACEHOLDER_MEASUREMENT_ID"
  });
  // Override authDomain to the actual serving domain.
  // This is required for iOS Safari/Chrome — otherwise Firebase redirects
  // through firebaseapp.com which iOS blocks (ITP cross-origin session loss).
  // NOTE: requires https://[hostname]/__/auth/handler to be registered in
  // Google Cloud Console → OAuth 2.0 Client → Authorized redirect URIs.
  if (window.location.hostname !== 'localhost' && window.location.hostname !== '127.0.0.1') {
    _creds.authDomain = window.location.hostname;
  }
  firebase.initializeApp(_creds);
}

// Auth state observer — handlers are defined in firebase-globals.js.
firebase.auth().onAuthStateChanged(function(user) {
  if (user) {
    console.log('✓ User signed in:', user.email);
    if (typeof onUserSignedIn === 'function') onUserSignedIn(user);
  } else {
    console.log('✗ User signed out');
    if (typeof onUserSignedOut === 'function') onUserSignedOut();
  }
});
