/**
 * Firebase Configuration
 * =====================
 * Credentials come from js/firebase-credentials.js (window.FIREBASE_CREDS),
 * which is generated by GitHub Actions from the FIREBASE_CONFIG secret.
 * This file is NEVER overwritten by CI — all logic lives here safely.
 */

function initFirebaseRuntime() {
  if (window.__firebaseRuntimeInitialized) return;
  window.__firebaseRuntimeInitialized = true;

  // Initialize Firebase (only once).
  // Credentials come from firebase-credentials.js (window.FIREBASE_CREDS).
  // Avoid declaring `const firebaseConfig` — the credentials file (written by
  // GitHub Actions secret) may already declare it, causing a SyntaxError.
  if (!firebase.apps.length) {
    firebase.initializeApp(window.FIREBASE_CREDS || {
      apiKey: "PLACEHOLDER_API_KEY",
      authDomain: "PLACEHOLDER_AUTHDOMAIN",
      projectId: "PLACEHOLDER_PROJECT_ID",
      storageBucket: "PLACEHOLDER_BUCKET",
      messagingSenderId: "PLACEHOLDER_SENDER_ID",
      appId: "PLACEHOLDER_APP_ID",
      measurementId: "PLACEHOLDER_MEASUREMENT_ID"
    });
  }

  // ── Offline persistence ────────────────────────────────────────────────
  // Enables IndexedDB cache for Firestore. With this active:
  //   • Reads served from local cache when offline.
  //   • Writes performed offline are queued in IndexedDB and synced to
  //     the server automatically when the network returns.
  //   • Latency-compensated UI: a saveDeck() call returns instantly even
  //     offline; the doc appears in queries immediately and is reconciled
  //     with the server later.
  //
  // Must be called BEFORE any firestore() read/write — this file runs
  // before firebase-globals.js which is the first consumer.
  //
  // Try multi-tab first (so two open browser tabs can share the cache),
  // then fall back to single-tab if multi-tab is rejected. iOS Safari
  // standalone PWAs in particular can fail multi-tab with
  // failed-precondition because the BroadcastChannel coordination layer
  // behaves oddly across PWA / Safari-tab pairs. Single-tab still
  // delivers everything the user needs (decks visible across sessions,
  // offline writes queued) — we just lose cross-tab coordination,
  // which is a non-issue in standalone mode.
  //
  // window.__firestorePersistenceReady resolves when persistence is
  // enabled (or false if both attempts failed).
  window.__firestorePersistenceReady = (function() {
    var fs = firebase.firestore();

    // The COMPAT SDK exposes IndexedDB persistence through the instance
    // method enablePersistence({synchronizeTabs}) — NOT the modular
    // function names enableIndexedDbPersistence() / initializeFirestore(),
    // which are not present on the compat firestore() object. An earlier
    // version guarded on those modular names, so it always fell through to
    // the in-memory branch and persistence was never actually on. We
    // feature-detect the real compat method here.
    if (typeof fs.enablePersistence !== 'function') {
      window.__firestorePersistenceEnabled = false;
      window.__firestorePersistenceError = 'api-removed';
      console.info(
        '[Firestore] enablePersistence() not available in this SDK build; ' +
        'decks will be in-memory for this session.'
      );
      return Promise.resolve(false);
    }

    // Single-tab persistence: each tab keeps its own IndexedDB cache.
    function applySingleTab() {
      return fs.enablePersistence()
        .then(function() {
          window.__firestorePersistenceEnabled = true;
          window.__firestorePersistenceMode = 'single-tab';
          console.info('[Firestore] Offline persistence enabled (single-tab)');
          return true;
        })
        .catch(function(err) {
          window.__firestorePersistenceEnabled = false;
          window.__firestorePersistenceError = (err && err.code) || 'unknown';
          if (err && err.code === 'failed-precondition') {
            console.warn('[Firestore] Persistence unavailable: another tab already holds it. Decks will be in-memory only this session.');
          } else if (err && err.code === 'unimplemented') {
            console.warn('[Firestore] Persistence unsupported by this browser (private mode?). Decks will be in-memory only.');
          } else {
            console.warn('[Firestore] Single-tab persistence failed:', err);
          }
          return false;
        });
    }

    // Prefer multi-tab (synchronizeTabs) so two open tabs share one cache;
    // gracefully fall back to single-tab where multi-tab is rejected.
    return fs.enablePersistence({ synchronizeTabs: true })
      .then(function() {
        window.__firestorePersistenceEnabled = true;
        window.__firestorePersistenceMode = 'multi-tab';
        console.info('[Firestore] Offline persistence enabled (multi-tab)');
        return true;
      })
      .catch(function(err) {
        var code = err && err.code;
        if (code === 'unimplemented') {
          // Browser can't do IndexedDB persistence (e.g. private mode).
          window.__firestorePersistenceEnabled = false;
          window.__firestorePersistenceError = code;
          console.info('[Firestore] Persistence unsupported by this browser (private mode?). Decks will be in-memory only.');
          return false;
        }
        // failed-precondition (another tab) or anything else → try single-tab.
        console.info('[Firestore] Multi-tab persistence rejected (' + (code || 'unknown') + '); trying single-tab…');
        return applySingleTab();
      });
  })();

  // Auth state observer — handlers are defined in firebase-globals.js.
  const _fbDev = typeof DEV_MODE !== 'undefined' ? DEV_MODE : false;
  firebase.auth().onAuthStateChanged(function(user) {
    if (user) {
      console.info('[Auth] Firebase state: signed in', user.email || user.uid || 'unknown-user');
      if (_fbDev) console.log('✓ User signed in:', user.email);
      if (typeof onUserSignedIn === 'function') {
        onUserSignedIn(user);
      } else {
        window.__pendingAuthUser = user;
        console.warn('[Auth] onUserSignedIn handler not ready yet; queued auth state for later sync');
      }
    } else {
      console.info('[Auth] Firebase state: signed out');
      if (_fbDev) console.log('✗ User signed out');
      if (typeof onUserSignedOut === 'function') {
        onUserSignedOut();
      } else {
        window.__pendingAuthUser = null;
        console.warn('[Auth] onUserSignedOut handler not ready yet; queued auth state for later sync');
      }
    }
  });
}

// Run synchronously — the Firebase SDK scripts are already loaded at this point,
// and firebase-globals.js (next in load order) needs firebase.auth() immediately.
initFirebaseRuntime();
