"""Cross-surface consistency between the bot deck index, the website's
matchup CSV, and the deck-name source the website dropdowns read.

The bot, the "Matchups vs Meta Call" panel, and the deck-select
dropdown on /current-analysis all build their UI from the same data
roots. Diffs between them are user-visible bugs (numbers that don't
match across two tabs, deep-links that land on a tab but don't
pre-select the deck, etc.). This suite pins:

  • Bot's current-meta matchup values agree with the raw Limitless
    online CSV — but tolerates the labs blend on pairs that have
    enough labs samples (MAJOR_MATCHUP_MIN_GAMES = 10).
  • Every bot deck name is present in the website source the
    dropdown reads — so each deep-link's ?deck=… actually pre-selects
    an option instead of leaving the field blank.
  • Deep-link URL encoding round-trips for every deck (apostrophes,
    spaces, the works).

Sources:
  • Bot deck index: data/bot-deck-index.json (generated by
    scripts/generate-bot-deck-index.py during the Pages deploy).
  • Website matchup source: data/limitless_online_decks_matchups.csv
    (read raw by js/app-current-meta-analysis.js:1804).
  • Website dropdown source: data/current_meta_card_data.csv
    archetype column (read by js/app-current-meta-analysis.js).
"""

import csv
import json
import os
import urllib.parse
from collections import defaultdict

import pytest

REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
# CI overrides DATA_DIR to _site/data after the build step so the
# cross-surface checks see the freshly-generated bot-deck-index.json.
# Local runs default to the source data/ tree.
DATA_DIR = os.environ.get("DATA_DIR") or os.path.join(REPO_ROOT, "data")
BOT_INDEX_PATH = os.path.join(DATA_DIR, "bot-deck-index.json")


# ──────────────────────────────────────────────────────────────────────
# Fixtures
# ──────────────────────────────────────────────────────────────────────

@pytest.fixture(scope="module")
def bot_index():
    """The bot index is only present after the Pages deploy generates it —
    in the data/ tree directly we have the source files but not the
    compiled artifact. Skip rather than fail when missing so dev runs
    don't error out before the first generate."""
    if not os.path.isfile(BOT_INDEX_PATH):
        pytest.skip("bot-deck-index.json not in data/ — run generate-bot-deck-index.py first")
    with open(BOT_INDEX_PATH, encoding="utf-8") as f:
        return json.load(f)


@pytest.fixture(scope="module")
def limitless_matchups():
    """{deck_name: {opponent: {'wr': float, 'games': int}}}"""
    path = os.path.join(DATA_DIR, "limitless_online_decks_matchups.csv")
    if not os.path.isfile(path):
        pytest.skip("limitless_online_decks_matchups.csv missing")
    out = defaultdict(dict)
    with open(path, encoding="utf-8-sig") as f:
        for r in csv.DictReader(f, delimiter=";"):
            d = (r.get("deck_name") or "").strip()
            o = (r.get("opponent") or "").strip()
            if not d or not o:
                continue
            try:
                wr = float((r.get("win_rate") or "0").replace(",", ".").replace("%", "").strip())
                g = int((r.get("total_games") or "0").strip())
            except (ValueError, TypeError):
                continue
            out[d][o] = {"wr": wr, "games": g}
    return out


@pytest.fixture(scope="module")
def website_current_archetypes():
    """Set of archetype names the /current-analysis dropdown will offer."""
    path = os.path.join(DATA_DIR, "current_meta_card_data.csv")
    if not os.path.isfile(path):
        pytest.skip("current_meta_card_data.csv missing")
    names = set()
    with open(path, encoding="utf-8-sig") as f:
        for r in csv.DictReader(f, delimiter=";"):
            arch = (r.get("archetype") or "").strip()
            if arch:
                names.add(arch)
    return names


@pytest.fixture(scope="module")
def website_past_archetypes():
    """Set of archetype names the /past-meta dropdown offers for TEF-POR."""
    path = os.path.join(DATA_DIR, "tournament_cards_data_cards_TEF-POR.csv")
    if not os.path.isfile(path):
        pytest.skip("tournament_cards_data_cards_TEF-POR.csv missing")
    names = set()
    with open(path, encoding="utf-8-sig") as f:
        for r in csv.DictReader(f, delimiter=";"):
            arch = (r.get("archetype") or "").strip()
            if arch:
                names.add(arch)
    return names


# ──────────────────────────────────────────────────────────────────────
# Tests
# ──────────────────────────────────────────────────────────────────────

# Same threshold the generator uses to decide whether to blend labs in
# (scripts/generate-bot-deck-index.py:MAJOR_MATCHUP_MIN_GAMES = 10).
# Pairs above this can legitimately differ from the raw online value;
# pairs below it must match the online value exactly.
MAJOR_MATCHUP_MIN_GAMES = 10


def test_bot_matchups_match_website_panel_when_no_blend(bot_index, limitless_matchups):
    """For each (deck, opponent) the bot surfaces, when no labs blend
    was applied (= labs sample below threshold), the win-pct must
    match the raw Limitless CSV exactly. Blended pairs are skipped —
    they're allowed to differ by design.

    The CSV holds win-rates as percentages with 0.1pp precision, so we
    tolerate a tiny floating-point delta only.
    """
    diffs = []
    for deck in bot_index.get("decks", {}).values():
        src = deck.get("sources", {}).get("current-meta")
        if not src:
            continue
        name = deck["name"]
        for m in src.get("matchups", []):
            opp = m.get("opponent")
            bot_wr = float(m.get("win_pct", 0))
            online = limitless_matchups.get(name, {}).get(opp)
            if not online:
                continue  # bot has the pair, website doesn't — different concern
            web_wr = online["wr"]
            # If the pair could have been blended, skip the strict check
            web_games = online["games"]
            if bot_wr != round(web_wr, 1):
                # The drift can be due to labs blend (sample large enough)
                # or a real inconsistency. The bot's "games" field on a
                # blended pair is online + labs combined; on raw it equals
                # the online sample. Use that gap to spot the labs branch.
                if abs(m.get("games", 0) - web_games) > 0:
                    continue  # labs blended → legitimate diff
                diffs.append((name, opp, bot_wr, web_wr))
    assert not diffs, (
        "Bot shows different matchup numbers than the website panel for "
        "pairs that should be raw online (no labs blend):\n  "
        + "\n  ".join(f"{n} vs {o}: bot={b:.1f}% web={w:.1f}%" for n, o, b, w in diffs[:10])
    )


def test_bot_current_deck_names_exist_in_website_source(bot_index, website_current_archetypes):
    """Every name the bot embeds in a current-meta deep-link
    (#current-analysis?deck=…) must exist as an option in the
    /current-analysis dropdown — otherwise the user lands on the tab
    but the dropdown stays blank."""
    bot_names = {
        d["name"] for d in bot_index["decks"].values()
        if "current-meta" in d.get("sources", {})
    }
    missing = bot_names - website_current_archetypes
    assert not missing, (
        "Bot exposes current-meta decks that don't exist in the website's "
        "deck-select source (current_meta_card_data.csv archetype column). "
        "Deep-links to these decks will land on the tab but won't pre-select:\n  "
        + "\n  ".join(sorted(missing)[:10])
    )


def test_bot_past_deck_names_exist_in_website_source(bot_index, website_past_archetypes):
    """Same as above for past-meta deep-links (#past-meta?deck=…&format=TEF-POR)."""
    bot_names = {
        d["name"] for d in bot_index["decks"].values()
        if "past-tef-por" in d.get("sources", {})
    }
    missing = bot_names - website_past_archetypes
    assert not missing, (
        "Bot exposes past-tef-por decks that don't exist in the website's "
        "past-meta deck-select source. Deep-links to these decks will land "
        "but won't pre-select:\n  "
        + "\n  ".join(sorted(missing)[:10])
    )


def test_deep_link_urls_round_trip(bot_index):
    """Every deck name must survive URL-encoding and URL-decoding without
    drift. Apostrophes (N's Zoroark, Cynthia's Garchomp, etc.) and
    spaces are the usual hazards."""
    tab_for_source = {
        "current-meta": "current-analysis",
        "past-tef-por": "past-meta",
        "city-league":  "city-league-analysis",
    }
    issues = []
    for deck in bot_index["decks"].values():
        name = deck["name"]
        for src_key, src in deck.get("sources", {}).items():
            tab = tab_for_source.get(src_key)
            if not tab:
                continue
            qs = {"deck": name}
            if src_key == "past-tef-por" and src.get("format_key"):
                qs["format"] = src["format_key"]
            url = f"https://thedipidis.app/#{tab}?{urllib.parse.urlencode(qs)}"

            # Parse it back the way js/inline-init.js does
            frag = urllib.parse.urlparse(url).fragment
            if "?" not in frag:
                issues.append((name, src_key, "no query in fragment"))
                continue
            params = urllib.parse.parse_qs(frag.split("?", 1)[1])
            roundtripped = params.get("deck", [""])[0]
            if roundtripped != name:
                issues.append((name, src_key, f"roundtrip drift: {roundtripped!r}"))
    assert not issues, (
        "Deep-link URL encoding does not round-trip cleanly for some decks:\n  "
        + "\n  ".join(f"{n} / {s}: {why}" for n, s, why in issues[:10])
    )
