#!/usr/bin/env python3
"""Generate data/offline-manifest.json for the PWA prefetcher.

Called from .github/workflows/deploy-pages.yml during the Cache-bust
step so the manifest's file list + sizes stay accurate every deploy.

Usage:
    python3 scripts/generate-offline-manifest.py <data-dir> <version-stamp>

The manifest lists every .json / .csv / .html file at the top level of
<data-dir> that the offline prefetcher should warm into the SW cache.
Excludes _archive/ and per-archetype chunk dirs (those are dev-only,
never deployed), plus backup/debug/partial files.
"""

from __future__ import annotations

import json
import os
import sys


def build_manifest(data_dir: str, version_stamp: str) -> dict:
    files = []
    for entry in sorted(os.listdir(data_dir)):
        full = os.path.join(data_dir, entry)
        if not os.path.isfile(full):
            continue
        if not (entry.endswith(".json") or entry.endswith(".csv") or entry.endswith(".html")):
            continue
        if entry == "offline-manifest.json":
            continue
        if entry.startswith("debug_") or entry.endswith("_local.html"):
            continue
        if "_BACKUP_" in entry or "_OLD_" in entry or "_PARTIAL_" in entry:
            continue
        files.append({"path": entry, "size": os.path.getsize(full)})

    total = sum(f["size"] for f in files)
    return {
        "generated_at": version_stamp,
        "total_bytes": total,
        "total_mb": round(total / 1024 / 1024, 1),
        "file_count": len(files),
        "note": (
            "Auto-generated by deploy-pages.yml (scripts/generate-offline-manifest.py). "
            "List of data files the offline prefetcher warms into the SW cache."
        ),
        "files": files,
    }


def main(argv: list[str]) -> int:
    if len(argv) < 2:
        print("usage: generate-offline-manifest.py <data-dir> [version-stamp]", file=sys.stderr)
        return 2
    data_dir = argv[1]
    version_stamp = argv[2] if len(argv) >= 3 else ""
    if not os.path.isdir(data_dir):
        print(f"error: data-dir not found: {data_dir}", file=sys.stderr)
        return 1
    manifest = build_manifest(data_dir, version_stamp)
    out_path = os.path.join(data_dir, "offline-manifest.json")
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(manifest, f, indent=2)
    print(
        f"offline-manifest.json: {manifest['file_count']} files, "
        f"{manifest['total_mb']} MB → {out_path}"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
