#!/usr/bin/env python3
"""Generate data/offline-manifest.json + offline-images-manifest.json.

Called from .github/workflows/deploy-pages.yml during the Cache-bust
step so the manifests stay accurate every deploy.

Usage:
    python3 scripts/generate-offline-manifest.py <data-dir> <version-stamp>

The data manifest lists every .json / .csv / .html file at the top
level of <data-dir> that the offline prefetcher should warm into the
SW cache.  Excludes _archive/ and per-archetype chunk dirs (dev-only,
never deployed), plus backup/debug/partial files.

The image manifest lists every card image URL from
cards_chunk_standard.json — the "Standard-rotation" slice the user
sees in Card Database, Current Meta, City League, and saved decks
built from the active rotation. We deliberately skip
cards_chunk_extended.json / cards_chunk_legacy.json (~16k extra
images, ~8 GB) because most offline users won't browse those and
the SW will still lazy-cache anything they do click on while online.
"""

from __future__ import annotations

import json
import os
import sys


def build_data_manifest(data_dir: str, version_stamp: str) -> dict:
    files = []
    for entry in sorted(os.listdir(data_dir)):
        full = os.path.join(data_dir, entry)
        if not os.path.isfile(full):
            continue
        if not (entry.endswith(".json") or entry.endswith(".csv") or entry.endswith(".html")):
            continue
        if entry in ("offline-manifest.json", "offline-images-manifest.json"):
            continue
        if entry.startswith("debug_") or entry.endswith("_local.html"):
            continue
        if "_BACKUP_" in entry or "_OLD_" in entry or "_PARTIAL_" in entry:
            continue
        files.append({"path": entry, "size": os.path.getsize(full)})

    total = sum(f["size"] for f in files)
    return {
        "generated_at": version_stamp,
        "total_bytes": total,
        "total_mb": round(total / 1024 / 1024, 1),
        "file_count": len(files),
        "note": (
            "Auto-generated by deploy-pages.yml (scripts/generate-offline-manifest.py). "
            "List of data files the offline prefetcher warms into the SW cache."
        ),
        "files": files,
    }


def build_images_manifest(data_dir: str, version_stamp: str) -> dict:
    """Collect card image URLs from the Standard-rotation chunk +
    every energy card from extended / legacy chunks.

    cards_chunk_standard.json drives the Card Database tab's default
    view. We deliberately skip the bulk of extended/legacy (thousands
    of niche / old cards, multi-GB) BUT we must still cache energies
    from those chunks because Basic Energy reprints (Grass / Fire /
    Water / Psychic / Fighting / Lightning / Darkness / Metal / Fairy)
    live in older sets that aren't in standard — every competitive
    deck has 5-15 energy cards, so omitting them leaves visible holes
    in offline deck views (reported 2026-05-29 08:14).
    """
    urls: list[str] = []
    seen: set[str] = set()

    def collect_from(path: str, predicate=None) -> int:
        added = 0
        if not os.path.exists(path):
            return 0
        try:
            with open(path, encoding="utf-8") as f:
                payload = json.load(f)
        except Exception as exc:
            print(f"warn: could not parse {path}: {exc}", file=sys.stderr)
            return 0
        cards = payload.get("cards") if isinstance(payload, dict) else payload
        if not isinstance(cards, list):
            return 0
        for card in cards:
            if not isinstance(card, dict):
                continue
            if predicate and not predicate(card):
                continue
            url = card.get("image_url")
            if not url or not isinstance(url, str) or not url.startswith("https://"):
                continue
            if url in seen:
                continue
            seen.add(url)
            urls.append(url)
            added += 1
        return added

    standard_count = collect_from(os.path.join(data_dir, "cards_chunk_standard.json"))

    # Energy cards from the wider chunks. Predicate matches both
    # "Basic Energy" and "Special Energy" (Trekking Shoes, Jet Energy
    # etc. are widely played and small in number).
    def is_energy(c: dict) -> bool:
        typ = (c.get("type") or "").strip()
        if typ.startswith("Basic Energy") or typ.startswith("Special Energy"):
            return True
        name = (c.get("name_en") or c.get("name") or "").strip()
        # Catch the nine basic energies plus any name ending in "Energy"
        # — false positives here only cost a few extra cached images.
        if name.endswith(" Energy"):
            return True
        return False

    extended_count = collect_from(
        os.path.join(data_dir, "cards_chunk_extended.json"), is_energy
    )
    legacy_count = collect_from(
        os.path.join(data_dir, "cards_chunk_legacy.json"), is_energy
    )

    # Rough per-image estimate (limitless LG scans average ~500 KB)
    estimated_per_image = 500 * 1024
    estimated_total = len(urls) * estimated_per_image

    return {
        "generated_at": version_stamp,
        "url_count": len(urls),
        "breakdown": {
            "standard_chunk": standard_count,
            "extended_energies": extended_count,
            "legacy_energies": legacy_count,
        },
        "estimated_per_image_bytes": estimated_per_image,
        "estimated_total_bytes": estimated_total,
        "estimated_total_mb": round(estimated_total / 1024 / 1024, 1),
        "source": "cards_chunk_standard.json + energies from extended/legacy",
        "note": (
            "Card art URLs the offline prefetcher should warm into the SW image cache. "
            "Cross-origin opaque responses — see IMAGE_CACHE_HOSTS in service-worker.js."
        ),
        "urls": urls,
    }


def main(argv: list[str]) -> int:
    if len(argv) < 2:
        print("usage: generate-offline-manifest.py <data-dir> [version-stamp]", file=sys.stderr)
        return 2
    data_dir = argv[1]
    version_stamp = argv[2] if len(argv) >= 3 else ""
    if not os.path.isdir(data_dir):
        print(f"error: data-dir not found: {data_dir}", file=sys.stderr)
        return 1

    data_manifest = build_data_manifest(data_dir, version_stamp)
    data_out = os.path.join(data_dir, "offline-manifest.json")
    with open(data_out, "w", encoding="utf-8") as f:
        json.dump(data_manifest, f, indent=2)
    print(
        f"offline-manifest.json: {data_manifest['file_count']} files, "
        f"{data_manifest['total_mb']} MB → {data_out}"
    )

    images_manifest = build_images_manifest(data_dir, version_stamp)
    images_out = os.path.join(data_dir, "offline-images-manifest.json")
    with open(images_out, "w", encoding="utf-8") as f:
        json.dump(images_manifest, f, indent=2)
    print(
        f"offline-images-manifest.json: {images_manifest['url_count']} URLs, "
        f"~{images_manifest['estimated_total_mb']} MB est. → {images_out}"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
