#!/usr/bin/env python3
"""Scrape pokemonproxies.com -> data/pokemonproxies_index.json.

pokemonproxies.com is a Vite SPA; every card image is imported as a static
asset, so the built JS bundle contains content-hashed filenames like
  5a-037-Dhelmise-BMPrMgp-.png   (setcode-number-Name-hash.png)
Parsing the bundle gives a complete (set, number) -> proxy image URL map.

We only keep the sets pokemonproxies actually proxies — the Japanese-only
Mega-era sets (e.g. "5a" == M5 "Abyss Eye") that have no international print,
which is exactly where the app would otherwise fall back to Japanese art.
International (EN/DE) cards keep their normal Limitless prints.

Fail-soft: on any error the existing committed JSON is left untouched.
"""
import json, os, re, sys, urllib.request

UA = {"User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124 Safari/537.36"}
BASE = "https://www.pokemonproxies.com"
OUT = os.path.join(os.path.dirname(__file__), "..", "data", "pokemonproxies_index.json")

# pokemonproxies set code -> our (Limitless/DB) set code. Extend as new
# Japanese-only sets get proxied. Only mapped codes are written.
# NACHTRAG 21.08.2026: Dieselbe Falle wie in
# backend/scrapers/scrape_pokemonproxies_urls.py — eine von Hand
# gepflegte Liste altert bei jedem japanischen Set. M6 (31.07.2026)
# stand hier nicht drin, also konnte diese Datei nur M5 finden.
# data/pokemonproxies_index.json enthaelt entsprechend 0 M6-Eintraege.
# Die Kuerzel folgen der Regel M<n> -> <n>a; welches Set laeuft, steht
# in data/format_window.json.
_SET_MAP_STATISCH = {
    "5a": "M5",   # Abyss Eye (JP Mega set) — Dunkelnacht line
}


def _baue_set_map(rueckwaerts: int = 3) -> dict:
    karte = dict(_SET_MAP_STATISCH)
    pfad = os.path.join(os.path.dirname(__file__), "..", "data", "format_window.json")
    try:
        with open(pfad, encoding="utf-8") as f:
            jp = str(json.load(f).get("current_set_jp") or "").strip().upper()
    except (OSError, ValueError):
        return karte
    m = re.fullmatch(r"M(\d{1,2})", jp)
    if not m:
        return karte
    nummer = int(m.group(1))
    for n in range(max(1, nummer - rueckwaerts), nummer + 1):
        karte[f"{n}a"] = f"M{n}"
    return karte


SET_MAP = _baue_set_map()

ASSET_RE = re.compile(r"([0-9a-z]{1,4}-\d{3}-[A-Za-z0-9'.()\-]+?-[A-Za-z0-9]{5,10}-?\.png)")


def fetch(url):
    return urllib.request.urlopen(urllib.request.Request(url, headers=UA), timeout=60).read().decode("utf-8", "replace")


def main():
    home = fetch(BASE + "/")
    m = re.search(r'src="(/assets/index-[^"]+\.js)"', home)
    if not m:
        print("::warning::could not locate JS bundle on pokemonproxies homepage")
        return 1
    js = fetch(BASE + m.group(1))
    assets = sorted(set(ASSET_RE.findall(js)))

    index = {}
    for fn in assets:
        mm = re.match(r"^([0-9a-z]+)-(\d+)-(.+?)-[A-Za-z0-9]+-?\.png$", fn)
        if not mm:
            continue
        code, num = mm.group(1), mm.group(2)
        ours = SET_MAP.get(code)
        if not ours:
            continue
        index[f"{ours}-{int(num)}"] = f"{BASE}/assets/{fn}"

    if not index:
        print("::warning::no mapped pokemonproxies assets found — keeping committed JSON")
        return 1

    out = {
        "_meta": {
            "note": "Set+number -> pokemonproxies.com proxy image URL. Source: pokemonproxies.com "
                    "Vite bundle (content-hashed asset filenames). Covers Japanese-only sets "
                    "(e.g. M5=Abyss Eye) that have no international print. "
                    "Regenerated by scripts/scrape_pokemonproxies.py.",
            "source": "pokemonproxies.com",
        },
        "images": dict(sorted(index.items())),
    }
    with open(OUT, "w", encoding="utf-8") as f:
        json.dump(out, f, ensure_ascii=False, indent=1)
    print(f"Wrote {OUT} — {len(index)} entries across {sorted(set(SET_MAP.values()))}")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except Exception as e:
        print(f"::warning::scrape_pokemonproxies failed: {e}")
        sys.exit(1)
